name: Auto Release on Official Commit

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Auto Release if "official" in commit title
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get latest commit message
        id: get_commit
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%s)
          echo "commit_msg=$COMMIT_MSG" >> $GITHUB_OUTPUT

      - name: Check if commit message contains "official"
        id: check_official
        run: |
          MSG="${{ steps.get_commit.outputs.commit_msg }}"
          TITLE=""
          TAG=""
          SHOULD_RELEASE="false"

          if [[ "$MSG" =~ official ]]; then
            # [] 안에 있는 내용 추출 (릴리즈 제목)
            if [[ "$MSG" =~ \[([^\]]+)\] ]]; then
              TITLE="${BASH_REMATCH[1]}"
            else
              TITLE="official-release"
            fi
            # {} 안에 있는 내용 추출 (릴리즈 태그)
            if [[ "$MSG" =~ \{([^\}]+)\} ]]; then
              TAG="${BASH_REMATCH[1]}"
            else
              TAG="$TITLE"
            fi
            SHOULD_RELEASE="true"
          fi

          echo "release_title=$TITLE" >> $GITHUB_OUTPUT
          echo "release_tag=$TAG" >> $GITHUB_OUTPUT
          echo "should_release=$SHOULD_RELEASE" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        if: steps.check_official.outputs.should_release == 'true'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.check_official.outputs.release_title }}
          tag_name: ${{ steps.check_official.outputs.release_tag }}
          generate_release_notes: true
