name: Release build
run-name: Release ${{ github.event.inputs.tag_name }}

permissions:
  contents: write
  actions: read

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Release tag (e.g. v1.0.0)"
        required: true
        default: "V"
      release_title:
        description: "Release title"
        required: true
        default: "V"
      release_body:
        description: "Release notes (Markdown supported)"
        required: false
        default: ""
      draft:
        description: "Create as draft?"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
      release_type:
        description: "Release type"
        required: true
        default: "release"
        type: choice
        options:
          - "release"
          - "pre-release"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Download latest artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          workflow_conclusion: success
          name: android-release-apk
          path: extracted

      - name: Check extracted files
        run: ls -R extracted

      - name: Create GitHub Release (Markdown supported)
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_title }}
          body: ${{ github.event.inputs.release_body }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.release_type == 'pre-release' }}
          artifacts: extracted/tech.treeentertainment.treekiosk.v4.apk
          artifactContentType: "application/vnd.android.package-archive"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
